function [fitresult, gof, opts] = create_fit_NFCF(z_range, Phifit_range)
%CREATEFIT1(Z_RANGE,PHIFIT_RANGE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : z_range
%      Y Output: Phifit_range
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-May-2018 13:50:43


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( z_range, Phifit_range );

% Set up fittype and options.
ft = fittype( '(mean(z_range)./mean(z_range)).*( a4 + a1.*z_range + ((a2.*z_range).^a3) ) ./ ( a1.*z_range + ((a2.*z_range).^a3) )', 'independent', 'z_range', 'dependent', 'Phi' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );

opts.Lower = [0.1 0.1 0.1 0.1];
opts.StartPoint = [1.35 2.5 3.2 1];
opts.Upper = [10 10 20 10];

% Fit model to data.
[fitresult, gof, opts] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Phi (gfit) vs. z', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel 'z (-)'
ylabel 'Phi(-)'



